-- 000001_init_schema.down.sql
BEGIN;

DROP TABLE IF EXISTS fine_tune_records CASCADE;
DROP TABLE IF EXISTS trades CASCADE;
DROP TABLE IF EXISTS signals CASCADE;
DROP TABLE IF EXISTS indicator_weights CASCADE;
DROP TABLE IF EXISTS news_items CASCADE;
DROP TABLE IF EXISTS candles CASCADE;

COMMIT;
