package market

import "strings"

// AssetDefinition details a tradeable asset in Simple-Trader.
type AssetDefinition struct {
	Symbol        string  `json:"symbol"`         // Standardized internal symbol (e.g., "BTC/USDT", "COPPER/USDT")
	Name          string  `json:"name"`           // Display name (e.g. "Bitcoin", "Copper Futures")
	Bucket        string  `json:"bucket"`         // "CORE" or "ALPHA"
	ExposureGroup string  `json:"exposure_group"` // Bundle group (e.g. "GOLD", "SILVER", "COPPER", "OIL")
	FeedSource    string  `json:"feed_source"`    // "BINANCE", "KUCOIN", "COINEX", "YAHOO", "TRADINGVIEW"
	SourceParam   string  `json:"source_param"`   // Query parameter for exchange API (e.g. "BTCUSDT", "COPPERUSDT", "CL=F")
	MinSize       float64 `json:"min_size"`       // Minimum contract/token order quantity
	Decimals      int     `json:"decimals"`       // Price formatting decimals
}

// SupportedAssets returns the list of active Core and Alpha global crypto and commodity assets.
// Core assets are strictly commodities (Precious Metals, Industrial Metals, Energy).
// Alpha assets are liquid cryptocurrencies.
var SupportedAssets = []AssetDefinition{
	// --- CORE ASSETS (Commodities & Wealth Preservation / Inflation Hedges) ---
	// 1. Gold Exposure Group (Tokenized & Futures Assets)
	{
		Symbol:        "PAXG/USDT",
		Name:          "PAX Gold (Tokenized Gold)",
		Bucket:        "CORE",
		ExposureGroup: "GOLD",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "PAXGUSDT",
		MinSize:       0.001,
		Decimals:      2,
	},
	{
		Symbol:        "XAU/USDT",
		Name:          "Gold Futures",
		Bucket:        "CORE",
		ExposureGroup: "GOLD",
		FeedSource:    "BINANCE_FUTURES",
		SourceParam:   "XAUUSDT",
		MinSize:       0.001,
		Decimals:      2,
	},

	// 2. Silver Exposure Group
	{
		Symbol:        "XAG/USDT",
		Name:          "Silver Futures",
		Bucket:        "CORE",
		ExposureGroup: "SILVER",
		FeedSource:    "BINANCE_FUTURES",
		SourceParam:   "XAGUSDT",
		MinSize:       0.01,
		Decimals:      2,
	},

	// 3. Copper Exposure Group (Industrial Electrification)
	{
		Symbol:        "COPPER/USDT",
		Name:          "Copper Futures",
		Bucket:        "CORE",
		ExposureGroup: "COPPER",
		FeedSource:    "BINANCE_FUTURES",
		SourceParam:   "COPPERUSDT",
		MinSize:       0.1,
		Decimals:      3,
	},

	// 4. Platinum Exposure Group (Precious / Green Hydrogen Catalyst)
	{
		Symbol:        "XPT/USDT",
		Name:          "Platinum Futures",
		Bucket:        "CORE",
		ExposureGroup: "PLATINUM",
		FeedSource:    "BINANCE_FUTURES",
		SourceParam:   "XPTUSDT",
		MinSize:       0.01,
		Decimals:      2,
	},

	// 5. Palladium Exposure Group (Precious / Automotive & Electronics)
	{
		Symbol:        "XPD/USDT",
		Name:          "Palladium Futures",
		Bucket:        "CORE",
		ExposureGroup: "PALLADIUM",
		FeedSource:    "BINANCE_FUTURES",
		SourceParam:   "XPDUSDT",
		MinSize:       0.01,
		Decimals:      2,
	},

	// 6. Crude Oil Exposure Group (Macro Energy)
	{
		Symbol:        "OIL/USDT",
		Name:          "WTI Crude Oil",
		Bucket:        "CORE",
		ExposureGroup: "OIL",
		FeedSource:    "YAHOO",
		SourceParam:   "CL=F",
		MinSize:       0.1,
		Decimals:      2,
	},

	// 7. Aluminum Exposure Group (Industrial Lightweight Metals)
	{
		Symbol:        "ALU/USDT",
		Name:          "Aluminum Futures",
		Bucket:        "CORE",
		ExposureGroup: "ALUMINUM",
		FeedSource:    "YAHOO",
		SourceParam:   "ALI=F",
		MinSize:       0.1,
		Decimals:      2,
	},

	// 8. Natural Gas Exposure Group (Macro Energy)
	{
		Symbol:        "NG/USDT",
		Name:          "Natural Gas Futures",
		Bucket:        "CORE",
		ExposureGroup: "NATGAS",
		FeedSource:    "YAHOO",
		SourceParam:   "NG=F",
		MinSize:       0.1,
		Decimals:      3,
	},

	// 9. Brent Crude Exposure Group (Macro Energy, shares OIL group with WTI)
	{
		Symbol:        "BRENT/USDT",
		Name:          "Crude Oil Brent Futures",
		Bucket:        "CORE",
		ExposureGroup: "OIL",
		FeedSource:    "YAHOO",
		SourceParam:   "BZ=F",
		MinSize:       0.1,
		Decimals:      2,
	},

	// --- ALPHA ASSETS (Universally Supported Top Tier Liquid Crypto) ---
	{
		Symbol:        "BTC/USDT",
		Name:          "Bitcoin",
		Bucket:        "ALPHA",
		ExposureGroup: "BTC",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "BTCUSDT",
		MinSize:       0.0001,
		Decimals:      2,
	},
	{
		Symbol:        "ETH/USDT",
		Name:          "Ethereum",
		Bucket:        "ALPHA",
		ExposureGroup: "ETH",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "ETHUSDT",
		MinSize:       0.001,
		Decimals:      2,
	},
	{
		Symbol:        "SOL/USDT",
		Name:          "Solana",
		Bucket:        "ALPHA",
		ExposureGroup: "SOL",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "SOLUSDT",
		MinSize:       0.01,
		Decimals:      2,
	},
	{
		Symbol:        "BNB/USDT",
		Name:          "BNB",
		Bucket:        "ALPHA",
		ExposureGroup: "BNB",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "BNBUSDT",
		MinSize:       0.01,
		Decimals:      2,
	},
	{
		Symbol:        "XRP/USDT",
		Name:          "XRP",
		Bucket:        "ALPHA",
		ExposureGroup: "XRP",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "XRPUSDT",
		MinSize:       1.0,
		Decimals:      4,
	},
	{
		Symbol:        "DOGE/USDT",
		Name:          "Dogecoin",
		Bucket:        "ALPHA",
		ExposureGroup: "DOGE",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "DOGEUSDT",
		MinSize:       1.0,
		Decimals:      4,
	},
	{
		Symbol:        "ADA/USDT",
		Name:          "Cardano",
		Bucket:        "ALPHA",
		ExposureGroup: "ADA",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "ADAUSDT",
		MinSize:       1.0,
		Decimals:      4,
	},
	{
		Symbol:        "AVAX/USDT",
		Name:          "Avalanche",
		Bucket:        "ALPHA",
		ExposureGroup: "AVAX",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "AVAXUSDT",
		MinSize:       0.1,
		Decimals:      3,
	},
	{
		Symbol:        "SUI/USDT",
		Name:          "Sui",
		Bucket:        "ALPHA",
		ExposureGroup: "SUI",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "SUIUSDT",
		MinSize:       1.0,
		Decimals:      4,
	},
	{
		Symbol:        "LINK/USDT",
		Name:          "Chainlink",
		Bucket:        "ALPHA",
		ExposureGroup: "LINK",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "LINKUSDT",
		MinSize:       0.1,
		Decimals:      3,
	},
	{
		Symbol:        "DOT/USDT",
		Name:          "Polkadot",
		Bucket:        "ALPHA",
		ExposureGroup: "DOT",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "DOTUSDT",
		MinSize:       0.1,
		Decimals:      3,
	},
	{
		Symbol:        "NEAR/USDT",
		Name:          "NEAR Protocol",
		Bucket:        "ALPHA",
		ExposureGroup: "NEAR",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "NEARUSDT",
		MinSize:       0.1,
		Decimals:      3,
	},
	{
		Symbol:        "LTC/USDT",
		Name:          "Litecoin",
		Bucket:        "ALPHA",
		ExposureGroup: "LTC",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "LTCUSDT",
		MinSize:       0.01,
		Decimals:      2,
	},
	{
		Symbol:        "BCH/USDT",
		Name:          "Bitcoin Cash",
		Bucket:        "ALPHA",
		ExposureGroup: "BCH",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "BCHUSDT",
		MinSize:       0.01,
		Decimals:      2,
	},
	{
		Symbol:        "UNI/USDT",
		Name:          "Uniswap",
		Bucket:        "ALPHA",
		ExposureGroup: "UNI",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "UNIUSDT",
		MinSize:       0.1,
		Decimals:      3,
	},
	{
		Symbol:        "APT/USDT",
		Name:          "Aptos",
		Bucket:        "ALPHA",
		ExposureGroup: "APT",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "APTUSDT",
		MinSize:       0.1,
		Decimals:      3,
	},
	{
		Symbol:        "TON/USDT",
		Name:          "Toncoin",
		Bucket:        "ALPHA",
		ExposureGroup: "TON",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "TONUSDT",
		MinSize:       0.1,
		Decimals:      3,
	},
	// --- TOP CMC ASSETS: CMC top-200 coins listed on Binance + KuCoin + CoinEx + Kraken ---
	{
		Symbol:        "TRX/USDT",
		Name:          "TRON",
		Bucket:        "ALPHA",
		ExposureGroup: "TRX",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "TRXUSDT",
		MinSize:       0.1,
		Decimals:      5,
	},
	{
		Symbol:        "ZEC/USDT",
		Name:          "Zcash",
		Bucket:        "ALPHA",
		ExposureGroup: "ZEC",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "ZECUSDT",
		MinSize:       0.001,
		Decimals:      2,
	},
	{
		Symbol:        "HYPE/USDT",
		Name:          "Hyperliquid",
		Bucket:        "ALPHA",
		ExposureGroup: "HYPE",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "HYPEUSDT",
		MinSize:       0.001,
		Decimals:      4,
	},
	{
		Symbol:        "XLM/USDT",
		Name:          "Stellar",
		Bucket:        "ALPHA",
		ExposureGroup: "XLM",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "XLMUSDT",
		MinSize:       1,
		Decimals:      5,
	},
	{
		Symbol:        "HBAR/USDT",
		Name:          "Hedera",
		Bucket:        "ALPHA",
		ExposureGroup: "HBAR",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "HBARUSDT",
		MinSize:       1,
		Decimals:      5,
	},
	{
		Symbol:        "TAO/USDT",
		Name:          "Bittensor",
		Bucket:        "ALPHA",
		ExposureGroup: "TAO",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "TAOUSDT",
		MinSize:       0.0001,
		Decimals:      3,
	},
	{
		Symbol:        "SHIB/USDT",
		Name:          "Shiba Inu",
		Bucket:        "ALPHA",
		ExposureGroup: "SHIB",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "SHIBUSDT",
		MinSize:       1,
		Decimals:      6,
	},
	{
		Symbol:        "ONDO/USDT",
		Name:          "Ondo",
		Bucket:        "ALPHA",
		ExposureGroup: "ONDO",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "ONDOUSDT",
		MinSize:       0.1,
		Decimals:      5,
	},
	{
		Symbol:        "ENA/USDT",
		Name:          "Ethena",
		Bucket:        "ALPHA",
		ExposureGroup: "ENA",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "ENAUSDT",
		MinSize:       0.01,
		Decimals:      5,
	},
	{
		Symbol:        "AAVE/USDT",
		Name:          "Aave",
		Bucket:        "ALPHA",
		ExposureGroup: "AAVE",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "AAVEUSDT",
		MinSize:       0.001,
		Decimals:      3,
	},
	{
		Symbol:        "ASTER/USDT",
		Name:          "Aster",
		Bucket:        "ALPHA",
		ExposureGroup: "ASTER",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "ASTERUSDT",
		MinSize:       0.01,
		Decimals:      5,
	},
	{
		Symbol:        "PEPE/USDT",
		Name:          "Pepe",
		Bucket:        "ALPHA",
		ExposureGroup: "PEPE",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "PEPEUSDT",
		MinSize:       1,
		Decimals:      6,
	},
	{
		Symbol:        "PUMP/USDT",
		Name:          "Pump.fun",
		Bucket:        "ALPHA",
		ExposureGroup: "PUMP",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "PUMPUSDT",
		MinSize:       1,
		Decimals:      6,
	},
	{
		Symbol:        "ICP/USDT",
		Name:          "Internet Computer",
		Bucket:        "ALPHA",
		ExposureGroup: "ICP",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "ICPUSDT",
		MinSize:       0.01,
		Decimals:      4,
	},
	{
		Symbol:        "SKY/USDT",
		Name:          "Sky",
		Bucket:        "ALPHA",
		ExposureGroup: "SKY",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "SKYUSDT",
		MinSize:       1,
		Decimals:      5,
	},
	{
		Symbol:        "WLD/USDT",
		Name:          "Worldcoin",
		Bucket:        "ALPHA",
		ExposureGroup: "WLD",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "WLDUSDT",
		MinSize:       0.1,
		Decimals:      5,
	},
	{
		Symbol:        "ETC/USDT",
		Name:          "Ethereum Classic",
		Bucket:        "ALPHA",
		ExposureGroup: "ETC",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "ETCUSDT",
		MinSize:       0.01,
		Decimals:      4,
	},
	{
		Symbol:        "MORPHO/USDT",
		Name:          "Morpho",
		Bucket:        "ALPHA",
		ExposureGroup: "MORPHO",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "MORPHOUSDT",
		MinSize:       0.01,
		Decimals:      4,
	},
	{
		Symbol:        "ARB/USDT",
		Name:          "Arbitrum",
		Bucket:        "ALPHA",
		ExposureGroup: "ARB",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "ARBUSDT",
		MinSize:       0.1,
		Decimals:      5,
	},
	{
		Symbol:        "POL/USDT",
		Name:          "Polygon (prev. MATIC)",
		Bucket:        "ALPHA",
		ExposureGroup: "POL",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "POLUSDT",
		MinSize:       0.1,
		Decimals:      5,
	},
	{
		Symbol:        "QNT/USDT",
		Name:          "Quant",
		Bucket:        "ALPHA",
		ExposureGroup: "QNT",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "QNTUSDT",
		MinSize:       0.001,
		Decimals:      4,
	},
	{
		Symbol:        "ALGO/USDT",
		Name:          "Algorand",
		Bucket:        "ALPHA",
		ExposureGroup: "ALGO",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "ALGOUSDT",
		MinSize:       1,
		Decimals:      5,
	},
	{
		Symbol:        "JUP/USDT",
		Name:          "Jupiter",
		Bucket:        "ALPHA",
		ExposureGroup: "JUP",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "JUPUSDT",
		MinSize:       0.1,
		Decimals:      5,
	},
	{
		Symbol:        "RENDER/USDT",
		Name:          "Render",
		Bucket:        "ALPHA",
		ExposureGroup: "RENDER",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "RENDERUSDT",
		MinSize:       0.01,
		Decimals:      4,
	},
	{
		Symbol:        "ATOM/USDT",
		Name:          "Cosmos",
		Bucket:        "ALPHA",
		ExposureGroup: "ATOM",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "ATOMUSDT",
		MinSize:       0.01,
		Decimals:      4,
	},
	{
		Symbol:        "JST/USDT",
		Name:          "JUST",
		Bucket:        "ALPHA",
		ExposureGroup: "JST",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "JSTUSDT",
		MinSize:       0.1,
		Decimals:      5,
	},
	{
		Symbol:        "CAKE/USDT",
		Name:          "PancakeSwap",
		Bucket:        "ALPHA",
		ExposureGroup: "CAKE",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "CAKEUSDT",
		MinSize:       0.01,
		Decimals:      4,
	},
	{
		Symbol:        "FIL/USDT",
		Name:          "Filecoin",
		Bucket:        "ALPHA",
		ExposureGroup: "FIL",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "FILUSDT",
		MinSize:       0.01,
		Decimals:      4,
	},
	{
		Symbol:        "DASH/USDT",
		Name:          "Dash",
		Bucket:        "ALPHA",
		ExposureGroup: "DASH",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "DASHUSDT",
		MinSize:       0.001,
		Decimals:      4,
	},
	{
		Symbol:        "INJ/USDT",
		Name:          "Injective",
		Bucket:        "ALPHA",
		ExposureGroup: "INJ",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "INJUSDT",
		MinSize:       0.01,
		Decimals:      4,
	},
	{
		Symbol:        "VET/USDT",
		Name:          "VeChain",
		Bucket:        "ALPHA",
		ExposureGroup: "VET",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "VETUSDT",
		MinSize:       0.1,
		Decimals:      6,
	},
	{
		Symbol:        "AERO/USDT",
		Name:          "Aerodrome Finance",
		Bucket:        "ALPHA",
		ExposureGroup: "AERO",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "AEROUSDT",
		MinSize:       0.1,
		Decimals:      5,
	},
	{
		Symbol:        "ETHFI/USDT",
		Name:          "ether.fi",
		Bucket:        "ALPHA",
		ExposureGroup: "ETHFI",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "ETHFIUSDT",
		MinSize:       0.1,
		Decimals:      5,
	},
	{
		Symbol:        "PENGU/USDT",
		Name:          "Pudgy Penguins",
		Bucket:        "ALPHA",
		ExposureGroup: "PENGU",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "PENGUUSDT",
		MinSize:       1,
		Decimals:      6,
	},
	{
		Symbol:        "TRUMP/USDT",
		Name:          "OFFICIAL TRUMP",
		Bucket:        "ALPHA",
		ExposureGroup: "TRUMP",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "TRUMPUSDT",
		MinSize:       0.001,
		Decimals:      4,
	},
	{
		Symbol:        "STX/USDT",
		Name:          "Stacks",
		Bucket:        "ALPHA",
		ExposureGroup: "STX",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "STXUSDT",
		MinSize:       0.1,
		Decimals:      5,
	},
	{
		Symbol:        "RAY/USDT",
		Name:          "Raydium",
		Bucket:        "ALPHA",
		ExposureGroup: "RAY",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "RAYUSDT",
		MinSize:       0.1,
		Decimals:      4,
	},
	{
		Symbol:        "CRV/USDT",
		Name:          "Curve DAO Token",
		Bucket:        "ALPHA",
		ExposureGroup: "CRV",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "CRVUSDT",
		MinSize:       0.1,
		Decimals:      5,
	},
	{
		Symbol:        "ZRO/USDT",
		Name:          "LayerZero",
		Bucket:        "ALPHA",
		ExposureGroup: "ZRO",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "ZROUSDT",
		MinSize:       0.01,
		Decimals:      4,
	},
	{
		Symbol:        "PYTH/USDT",
		Name:          "Pyth Network",
		Bucket:        "ALPHA",
		ExposureGroup: "PYTH",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "PYTHUSDT",
		MinSize:       0.1,
		Decimals:      5,
	},
	{
		Symbol:        "FET/USDT",
		Name:          "Artificial Superintelligence Alliance",
		Bucket:        "ALPHA",
		ExposureGroup: "FET",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "FETUSDT",
		MinSize:       0.1,
		Decimals:      5,
	},
	{
		Symbol:        "VIRTUAL/USDT",
		Name:          "Virtuals Protocol",
		Bucket:        "ALPHA",
		ExposureGroup: "VIRTUAL",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "VIRTUALUSDT",
		MinSize:       0.1,
		Decimals:      5,
	},
	{
		Symbol:        "SEI/USDT",
		Name:          "Sei",
		Bucket:        "ALPHA",
		ExposureGroup: "SEI",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "SEIUSDT",
		MinSize:       0.1,
		Decimals:      5,
	},
	{
		Symbol:        "TIA/USDT",
		Name:          "Celestia",
		Bucket:        "ALPHA",
		ExposureGroup: "TIA",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "TIAUSDT",
		MinSize:       0.01,
		Decimals:      5,
	},
	{
		Symbol:        "PENDLE/USDT",
		Name:          "Pendle",
		Bucket:        "ALPHA",
		ExposureGroup: "PENDLE",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "PENDLEUSDT",
		MinSize:       0.1,
		Decimals:      4,
	},
	{
		Symbol:        "FF/USDT",
		Name:          "Falcon Finance",
		Bucket:        "ALPHA",
		ExposureGroup: "FF",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "FFUSDT",
		MinSize:       0.1,
		Decimals:      5,
	},
	{
		Symbol:        "NIGHT/USDT",
		Name:          "Midnight",
		Bucket:        "ALPHA",
		ExposureGroup: "NIGHT",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "NIGHTUSDT",
		MinSize:       1,
		Decimals:      5,
	},
	{
		Symbol:        "LDO/USDT",
		Name:          "Lido DAO",
		Bucket:        "ALPHA",
		ExposureGroup: "LDO",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "LDOUSDT",
		MinSize:       0.01,
		Decimals:      5,
	},
	{
		Symbol:        "XTZ/USDT",
		Name:          "Tezos",
		Bucket:        "ALPHA",
		ExposureGroup: "XTZ",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "XTZUSDT",
		MinSize:       0.1,
		Decimals:      5,
	},
	{
		Symbol:        "SUN/USDT",
		Name:          "Sun [New]",
		Bucket:        "ALPHA",
		ExposureGroup: "SUN",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "SUNUSDT",
		MinSize:       1,
		Decimals:      5,
	},
	{
		Symbol:        "BONK/USDT",
		Name:          "Bonk",
		Bucket:        "ALPHA",
		ExposureGroup: "BONK",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "BONKUSDT",
		MinSize:       1,
		Decimals:      6,
	},
	{
		Symbol:        "DCR/USDT",
		Name:          "Decred",
		Bucket:        "ALPHA",
		ExposureGroup: "DCR",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "DCRUSDT",
		MinSize:       0.001,
		Decimals:      4,
	},
	{
		Symbol:        "IMX/USDT",
		Name:          "Immutable",
		Bucket:        "ALPHA",
		ExposureGroup: "IMX",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "IMXUSDT",
		MinSize:       0.01,
		Decimals:      5,
	},
	{
		Symbol:        "OP/USDT",
		Name:          "Optimism",
		Bucket:        "ALPHA",
		ExposureGroup: "OP",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "OPUSDT",
		MinSize:       0.01,
		Decimals:      5,
	},
	{
		Symbol:        "XPL/USDT",
		Name:          "Plasma",
		Bucket:        "ALPHA",
		ExposureGroup: "XPL",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "XPLUSDT",
		MinSize:       0.1,
		Decimals:      5,
	},
	{
		Symbol:        "AR/USDT",
		Name:          "Arweave",
		Bucket:        "ALPHA",
		ExposureGroup: "AR",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "ARUSDT",
		MinSize:       0.01,
		Decimals:      4,
	},
	{
		Symbol:        "ENS/USDT",
		Name:          "Ethereum Name Service",
		Bucket:        "ALPHA",
		ExposureGroup: "ENS",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "ENSUSDT",
		MinSize:       0.01,
		Decimals:      4,
	},
	{
		Symbol:        "STRK/USDT",
		Name:          "Starknet",
		Bucket:        "ALPHA",
		ExposureGroup: "STRK",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "STRKUSDT",
		MinSize:       0.01,
		Decimals:      5,
	},
	{
		Symbol:        "GRT/USDT",
		Name:          "The Graph",
		Bucket:        "ALPHA",
		ExposureGroup: "GRT",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "GRTUSDT",
		MinSize:       1,
		Decimals:      5,
	},
	{
		Symbol:        "CFX/USDT",
		Name:          "Conflux",
		Bucket:        "ALPHA",
		ExposureGroup: "CFX",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "CFXUSDT",
		MinSize:       1,
		Decimals:      5,
	},
	{
		Symbol:        "FLOKI/USDT",
		Name:          "FLOKI",
		Bucket:        "ALPHA",
		ExposureGroup: "FLOKI",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "FLOKIUSDT",
		MinSize:       1,
		Decimals:      6,
	},
	{
		Symbol:        "SYRUP/USDT",
		Name:          "Maple Finance",
		Bucket:        "ALPHA",
		ExposureGroup: "SYRUP",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "SYRUPUSDT",
		MinSize:       0.1,
		Decimals:      5,
	},
	{
		Symbol:        "JTO/USDT",
		Name:          "Jito",
		Bucket:        "ALPHA",
		ExposureGroup: "JTO",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "JTOUSDT",
		MinSize:       0.1,
		Decimals:      5,
	},
	{
		Symbol:        "COMP/USDT",
		Name:          "Compound",
		Bucket:        "ALPHA",
		ExposureGroup: "COMP",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "COMPUSDT",
		MinSize:       0.001,
		Decimals:      4,
	},
	{
		Symbol:        "WIF/USDT",
		Name:          "dogwifhat",
		Bucket:        "ALPHA",
		ExposureGroup: "WIF",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "WIFUSDT",
		MinSize:       0.01,
		Decimals:      5,
	},
	{
		Symbol:        "EIGEN/USDT",
		Name:          "EigenCloud",
		Bucket:        "ALPHA",
		ExposureGroup: "EIGEN",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "EIGENUSDT",
		MinSize:       0.01,
		Decimals:      5,
	},
	{
		Symbol:        "JASMY/USDT",
		Name:          "JasmyCoin",
		Bucket:        "ALPHA",
		ExposureGroup: "JASMY",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "JASMYUSDT",
		MinSize:       0.1,
		Decimals:      6,
	},
	{
		Symbol:        "ZAMA/USDT",
		Name:          "Zama",
		Bucket:        "ALPHA",
		ExposureGroup: "ZAMA",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "ZAMAUSDT",
		MinSize:       1,
		Decimals:      5,
	},
	{
		Symbol:        "KMNO/USDT",
		Name:          "Kamino",
		Bucket:        "ALPHA",
		ExposureGroup: "KMNO",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "KMNOUSDT",
		MinSize:       1,
		Decimals:      5,
	},
	{
		Symbol:        "RUNE/USDT",
		Name:          "THORChain",
		Bucket:        "ALPHA",
		ExposureGroup: "RUNE",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "RUNEUSDT",
		MinSize:       0.1,
		Decimals:      5,
	},
	{
		Symbol:        "CVX/USDT",
		Name:          "Convex Finance",
		Bucket:        "ALPHA",
		ExposureGroup: "CVX",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "CVXUSDT",
		MinSize:       0.001,
		Decimals:      4,
	},
	{
		Symbol:        "2Z/USDT",
		Name:          "DoubleZero",
		Bucket:        "ALPHA",
		ExposureGroup: "2Z",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "2ZUSDT",
		MinSize:       1,
		Decimals:      5,
	},
	{
		Symbol:        "AXS/USDT",
		Name:          "Axie Infinity",
		Bucket:        "ALPHA",
		ExposureGroup: "AXS",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "AXSUSDT",
		MinSize:       0.01,
		Decimals:      4,
	},
	{
		Symbol:        "MINA/USDT",
		Name:          "Mina",
		Bucket:        "ALPHA",
		ExposureGroup: "MINA",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "MINAUSDT",
		MinSize:       0.1,
		Decimals:      5,
	},
	{
		Symbol:        "NEO/USDT",
		Name:          "Neo",
		Bucket:        "ALPHA",
		ExposureGroup: "NEO",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "NEOUSDT",
		MinSize:       0.01,
		Decimals:      4,
	},
	{
		Symbol:        "MET/USDT",
		Name:          "Meteora",
		Bucket:        "ALPHA",
		ExposureGroup: "MET",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "METUSDT",
		MinSize:       0.1,
		Decimals:      5,
	},
	{
		Symbol:        "MANA/USDT",
		Name:          "Decentraland",
		Bucket:        "ALPHA",
		ExposureGroup: "MANA",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "MANAUSDT",
		MinSize:       1,
		Decimals:      5,
	},
	{
		Symbol:        "CHZ/USDT",
		Name:          "Chiliz",
		Bucket:        "ALPHA",
		ExposureGroup: "CHZ",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "CHZUSDT",
		MinSize:       1,
		Decimals:      5,
	},
	{
		Symbol:        "A/USDT",
		Name:          "Vaulta",
		Bucket:        "ALPHA",
		ExposureGroup: "A",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "AUSDT",
		MinSize:       0.1,
		Decimals:      5,
	},
	{
		Symbol:        "SENT/USDT",
		Name:          "Sentient",
		Bucket:        "ALPHA",
		ExposureGroup: "SENT",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "SENTUSDT",
		MinSize:       1,
		Decimals:      5,
	},
	{
		Symbol:        "APE/USDT",
		Name:          "ApeCoin",
		Bucket:        "ALPHA",
		ExposureGroup: "APE",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "APEUSDT",
		MinSize:       0.01,
		Decimals:      5,
	},
	{
		Symbol:        "1INCH/USDT",
		Name:          "1inch",
		Bucket:        "ALPHA",
		ExposureGroup: "1INCH",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "1INCHUSDT",
		MinSize:       0.1,
		Decimals:      5,
	},
	{
		Symbol:        "BAT/USDT",
		Name:          "Basic Attention Token",
		Bucket:        "ALPHA",
		ExposureGroup: "BAT",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "BATUSDT",
		MinSize:       1,
		Decimals:      5,
	},
	{
		Symbol:        "EGLD/USDT",
		Name:          "MultiversX",
		Bucket:        "ALPHA",
		ExposureGroup: "EGLD",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "EGLDUSDT",
		MinSize:       0.01,
		Decimals:      4,
	},
	{
		Symbol:        "ZK/USDT",
		Name:          "ZKsync",
		Bucket:        "ALPHA",
		ExposureGroup: "ZK",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "ZKUSDT",
		MinSize:       0.1,
		Decimals:      5,
	},
	{
		Symbol:        "SAND/USDT",
		Name:          "The Sandbox",
		Bucket:        "ALPHA",
		ExposureGroup: "SAND",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "SANDUSDT",
		MinSize:       1,
		Decimals:      5,
	},
	{
		Symbol:        "PLUME/USDT",
		Name:          "Plume",
		Bucket:        "ALPHA",
		ExposureGroup: "PLUME",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "PLUMEUSDT",
		MinSize:       1,
		Decimals:      5,
	},
	{
		Symbol:        "GENIUS/USDT",
		Name:          "Genius Terminal",
		Bucket:        "ALPHA",
		ExposureGroup: "GENIUS",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "GENIUSUSDT",
		MinSize:       0.1,
		Decimals:      5,
	},
	{
		Symbol:        "S/USDT",
		Name:          "Sonic",
		Bucket:        "ALPHA",
		ExposureGroup: "S",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "SUSDT",
		MinSize:       0.1,
		Decimals:      5,
	},
	{
		Symbol:        "DYDX/USDT",
		Name:          "dYdX",
		Bucket:        "ALPHA",
		ExposureGroup: "DYDX",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "DYDXUSDT",
		MinSize:       0.01,
		Decimals:      5,
	},
	{
		Symbol:        "SUPER/USDT",
		Name:          "SuperVerse",
		Bucket:        "ALPHA",
		ExposureGroup: "SUPER",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "SUPERUSDT",
		MinSize:       1,
		Decimals:      5,
	},
	{
		Symbol:        "RSR/USDT",
		Name:          "Reserve Rights",
		Bucket:        "ALPHA",
		ExposureGroup: "RSR",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "RSRUSDT",
		MinSize:       0.1,
		Decimals:      6,
	},
	{
		Symbol:        "QTUM/USDT",
		Name:          "Qtum",
		Bucket:        "ALPHA",
		ExposureGroup: "QTUM",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "QTUMUSDT",
		MinSize:       0.1,
		Decimals:      4,
	},
	{
		Symbol:        "ZRX/USDT",
		Name:          "0x Protocol",
		Bucket:        "ALPHA",
		ExposureGroup: "ZRX",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "ZRXUSDT",
		MinSize:       1,
		Decimals:      5,
	},
	{
		Symbol:        "GALA/USDT",
		Name:          "Gala",
		Bucket:        "ALPHA",
		ExposureGroup: "GALA",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "GALAUSDT",
		MinSize:       1,
		Decimals:      6,
	},
	{
		Symbol:        "LSK/USDT",
		Name:          "Lisk",
		Bucket:        "ALPHA",
		ExposureGroup: "LSK",
		FeedSource:    "BINANCE_SPOT",
		SourceParam:   "LSKUSDT",
		MinSize:       0.1,
		Decimals:      5,
	},
}

// GetSupportedAssets returns the list of all supported assets.
func GetSupportedAssets() []AssetDefinition {
	return SupportedAssets
}

// FindAsset locates an asset definition by symbol (supports "BTC/USDT" or "BTCUSDT").
func FindAsset(symbol string) (AssetDefinition, bool) {
	cleanSym := strings.ToUpper(symbol)
	for _, a := range SupportedAssets {
		if a.Symbol == cleanSym {
			return a, true
		}
		if strings.ReplaceAll(a.Symbol, "/", "") == strings.ReplaceAll(cleanSym, "/", "") {
			return a, true
		}
	}
	return AssetDefinition{}, false
}

// GetBucket returns "CORE" or "ALPHA" dynamically based on the asset definition.
func GetBucket(symbol string) string {
	if def, ok := FindAsset(symbol); ok && def.Bucket != "" {
		return def.Bucket
	}
	return "ALPHA"
}

// GetExposureGroup returns the economic exposure bundle for the symbol.
// Gold commodities ("PAXG/USDT", "XAU/USDT") share the "GOLD" group
// to bundle identical physical/tokenized exposure and prevent splitting or duplicating cash.
func GetExposureGroup(symbol string) string {
	clean := strings.ToUpper(symbol)
	switch clean {
	case "PAXG/USDT", "XAU/USDT", "PAXGUSDT", "XAUUSDT":
		return "GOLD"
	case "XAG/USDT", "XAGUSDT":
		return "SILVER"
	case "COPPER/USDT", "COPPERUSDT":
		return "COPPER"
	case "XPT/USDT", "XPTUSDT":
		return "PLATINUM"
	case "XPD/USDT", "XPDUSDT":
		return "PALLADIUM"
	case "OIL/USDT", "BRENT/USDT", "OILUSDT", "BRENTUSDT", "CL=F", "BZ=F":
		return "OIL"
	case "NG/USDT", "NGUSDT", "NG=F":
		return "NATGAS"
	case "ALU/USDT", "ALUUSDT", "ALI=F":
		return "ALUMINUM"
	default:
		if def, ok := FindAsset(clean); ok && def.ExposureGroup != "" {
			return def.ExposureGroup
		}
		// Fall back to base coin (e.g. "BTC" for "BTC/USDT")
		parts := strings.Split(clean, "/")
		if len(parts) > 0 {
			return parts[0]
		}
		return clean
	}
}

// AreCorrelatedCommodities returns true if two symbols share the same underlying commodity exposure (e.g. PAXG & XAU).
func AreCorrelatedCommodities(symA, symB string) bool {
	if symA == symB {
		return true
	}
	grpA := GetExposureGroup(symA)
	grpB := GetExposureGroup(symB)
	if grpA == "" || grpB == "" {
		return false
	}
	// Only commodity groups are subject to correlated bundling constraints
	switch grpA {
	case "GOLD", "SILVER", "COPPER", "PLATINUM", "PALLADIUM", "OIL", "ALUMINUM", "NATGAS":
		return grpA == grpB
	default:
		return false
	}
}

// GetCorrelatedSymbols returns all symbols in the supported assets list that share the same exposure group.
func GetCorrelatedSymbols(symbol string) []string {
	targetGroup := GetExposureGroup(symbol)
	if targetGroup == "" {
		return []string{symbol}
	}
	var matches []string
	for _, a := range SupportedAssets {
		if a.ExposureGroup == targetGroup {
			matches = append(matches, a.Symbol)
		}
	}
	if len(matches) == 0 {
		return []string{symbol}
	}
	return matches
}
